version: '3'

services:
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - 8888:80
    depends_on:
      - php
    volumes:
      - .:/var/www/html
      - ./docker/web/conf.d/default.dev.conf:/etc/nginx/conf.d/default.conf
    networks:
      - php-playground

  php:
    container_name: slim
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    ports:
      - '9000:9000'
    volumes:
      - .:/var/www/html
    networks:
      - php-playground

networks:
  php-playground:
    driver: "bridge"